-- Create Admins Table
CREATE TABLE admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL
);

-- Insert Super Admin
INSERT INTO admins (email, password)
VALUES ('admin@adopta.com', 'Bla190305');
