-- Drop tables if they exist to start fresh (Clean Slate)
DROP TABLE IF EXISTS animals;
DROP TABLE IF EXISTS shelters;

-- Create Shelters Table
CREATE TABLE shelters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  city TEXT,
  province TEXT,
  location TEXT,
  donation_number TEXT,
  password TEXT, -- In a real app, this should be encrypted!
  status TEXT DEFAULT 'Pendiente',
  joined_date TIMESTAMPTZ DEFAULT NOW()
);

-- Create Animals Table
CREATE TABLE animals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  species TEXT CHECK (species IN ('Perro', 'Gato')),
  breed TEXT,
  age TEXT,
  size TEXT CHECK (size IN ('Pequeño', 'Mediano', 'Grande')),
  description TEXT,
  image TEXT,
  status TEXT DEFAULT 'Disponible',
  personality TEXT[],
  health TEXT,
  shelter_id BIGINT REFERENCES shelters(id) ON DELETE CASCADE
);

-- Optional: Insert a test shelter
INSERT INTO shelters (name, email, phone, city, province, location, donation_number, status, password)
VALUES ('Protectora Amigos Peludos', 'contacto@amigospeludos.com', '600123456', 'Madrid', 'Madrid', 'Calle Falsa 123', 'ES12345678', 'Activa', '123456');

-- Optional: Insert a test animal linked to the test shelter
INSERT INTO animals (name, species, breed, age, size, description, image, status, personality, health, shelter_id)
VALUES (
  'Max', 
  'Perro', 
  'Mestizo', 
  '2 años', 
  'Mediano', 
  'Max es un perro lleno de energía y amor.', 
  'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=800', 
  'Disponible', 
  ARRAY['Juguetón', 'Cariñoso'], 
  'Vacunado', 
  1
);
